name: chirp
description: Chirp - the newest microblogging.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  internet_connection_checker: ^0.0.1
  equatable: ^2.0.0
  dartz: ^0.10.0-nullsafety.1
  hive_flutter: ^1.0.0
  hive: ^2.0.0
  lint: ^1.5.3
  flutter_bloc: ^7.0.0
  dio: ^4.0.0-prev3
  get: ^4.0.0-nullsafety.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  
dev_dependencies:
  mocktail: ^0.1.1
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
